version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - '${FRONTEND_IMAGE}'
    image: '${FRONTEND_IMAGE}'
    ports:
      - "80:80"
  api:
    build:
      context: ./todo
      dockerfile: Dockerfile
      cache_from:
        - '${API_IMAGE}'
    image: '${API_IMAGE}'
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000