version: '3'
services:
  frontend:
    container_name: 'frontend'
    image: '${FRONTEND_IMAGE}'
    ports:
      - "443:80"
  api:
    container_name: 'api'
    image: '${API_IMAGE}'
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/todo/staticfiles/
      - media_volume:/todo/mediafiles/
    expose:
      - 8000
volumes:
  static_volume:
  media_volume: