version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  api:
    build:
      context: ./todo
      dockerfile: Dockerfile
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/todo/staticfiles/
      - media_volume:/todo/mediafiles/
    expose:
      - 8000
volumes:
  static_volume:
  media_volume: