version: '3'
services:
  api:
    container_name: 'api'
    image: '${API_IMAGE}'
    command: gunicorn todo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/todo/staticfiles/
      - media_volume:/todo/mediafiles/
    expose:
      - 8000
  nginx:
      container_name: 'nginx'
      image: '${NGINX_IMAGE}'
      ports:
        - 80:80
      volumes:
        - static_volume:/todo/staticfiles/
        - media_volume:/todo/mediafiles/
volumes:
  static_volume:
  media_volume: