# Generated by Django 4.2.14 on 2024-07-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0002_todo_target_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo", old_name="timestamp", new_name="created_at",
        ),
        migrations.RenameField(
            model_name="todo", old_name="target_time", new_name="target_time_at",
        ),
        migrations.RenameField(
            model_name="todo", old_name="updated", new_name="updated_at",
        ),
    ]
