# Generated by Django 4.2.14 on 2024-07-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0003_rename_timestamp_todo_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="color",
            field=models.CharField(default="#ffffff", max_length=15),
        ),
        migrations.AddField(
            model_name="todo",
            name="title",
            field=models.CharField(default="", max_length=60),
        ),
    ]
