# Generated by Django 4.2.14 on 2024-07-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0004_todo_color_todo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="bg_color",
            field=models.CharField(default="#ffffff", max_length=15),
        ),
        migrations.AlterField(
            model_name="todo",
            name="color",
            field=models.CharField(default="#000000", max_length=15),
        ),
    ]
