# Generated by Django 4.2.14 on 2024-07-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_api", "0005_todo_bg_color_alter_todo_color"),
    ]

    operations = [
        migrations.RemoveField(model_name="todo", name="completed",),
        migrations.RemoveField(model_name="todo", name="created_at",),
        migrations.RemoveField(model_name="todo", name="status",),
        migrations.RemoveField(model_name="todo", name="target_time_at",),
        migrations.RemoveField(model_name="todo", name="updated_at",),
    ]
