name: Continuous Integration and Delivery

on:
  push:
    branches:
      - production

env:
  FRONTEND_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/frontend
  API_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/api
  REGISTRY: ghcr.io


jobs:
  build:
    permissions: write-all
    name: Build the Docker Image
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: checkout main
        uses: actions/checkout@v3

      - name: Set environment variables to .env
        run: |
          echo "API_IMAGE=$(echo ${{env.API_IMAGE}} )" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE=$(echo ${{env.FRONTEND_IMAGE}} )" >> $GITHUB_ENV
      - name: Log in to GitHub Packages
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ github.repository_owner }}
        run: echo $PERSONAL_ACCESS_TOKEN | docker login ghcr.io -u "$USER_NAME" --password-stdin

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
      - name: Pull images
        run: |
          docker pull ${{ env.API_IMAGE }} || true
          docker pull ${{ env.FRONTEND_IMAGE }} || true
      - name: Build images
        id: build-images
        run: |
          docker-compose -f docker-compose.ci.yml build
      - name: Push images
        run: |
          docker push ${{ env.API_IMAGE }}
          docker push ${{ env.FRONTEND_IMAGE }}
  checking-secrets:
    name: Checking secrets
    runs-on: ubuntu-latest
    environment: production
    needs: build
    outputs:
      secret_key_exists: ${{steps.check_secrets.outputs.defined}}
    steps:
      - name: Check for Secrets availabilities
        id: check_secrets
        shell: bash
        run: |
          if [[ -n "${{ secrets.BASE64_PEM }}" ]]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "is undefined";
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    environment: production
    needs: checking-secrets
    if: needs.checking-secrets.outputs.secret_key_exists == 'true'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Add environment variables to .env
        run: |
          echo API_IMAGE=${{ env.API_IMAGE }} >> .env
          echo FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }} >> .env
          echo NAMESPACE=${{ github.repository_owner }} >> .env
          echo PERSONAL_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} >> .env
      - name: Decode SSH private key
        run: |
          echo "${{ secrets.BASE64_PEM }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          mv private_key.pem ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PUBLIC_IPV4_DNS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_rsa
      - name: Deploy images on AWS EC2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

        run: |
          scp -o StrictHostKeyChecking=no -r ./.env ./docker-compose.prod.yml ${{secrets.AWS_USER}}@${{ secrets.PUBLIC_IPV4_DNS }}:
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{secrets.AWS_USER}}@${{ secrets.PUBLIC_IPV4_DNS }} << EOF
              sudo docker-compose -f docker-compose.prod.yml down --rmi all -v
              echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
              sudo docker pull ${{ env.FRONTEND_IMAGE }}
              sudo docker pull ${{ env.API_IMAGE }}
              sudo docker-compose --env-file=.env -f docker-compose.prod.yml up -d --build
              sudo docker logout
          EOF