name: Continuous Integration and Delivery

on:
  push:
    branches:
      - production

env:
  #
  API_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/api
  NGINX_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/nginx
  REGISTRY: ghcr.io

#secrets:
#  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
  build:
    permissions: write-all
    name: Build the Docker Image
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: checkout main
        uses: actions/checkout@v3

      - name: Set environment variables to .env
        run: |
          echo "API_IMAGE=$(echo ${{env.API_IMAGE}} )" >> $GITHUB_ENV
          echo "NGINX_IMAGE=$(echo ${{env.NGINX_IMAGE}} )" >> $GITHUB_ENV
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v3
#        env:
#          PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          registry: ghcr.io
#          username: "${{ github.actor }}"
#          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to GitHub Packages
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ github.repository_owner }}
        run: echo $PERSONAL_ACCESS_TOKEN | docker login ghcr.io -u "$USER_NAME" --password-stdin

      - name: Pull images
        run: |
          docker pull ${{ env.API_IMAGE }} || true
          docker pull ${{ env.NGINX_IMAGE }} || true
      - name: Build images
        id: build-images
        run: |
          docker-compose -f docker-compose.ci.yml build
      - name: Push images
        run: |
          docker push ${{ env.API_IMAGE }}
          docker push ${{ env.NGINX_IMAGE }}
  checking-secrets:
    name: Checking secrets
    runs-on: ubuntu-latest
    environment: production

    # env:
    #   PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    needs: build
    outputs:
      secret_key_exists: ${{steps.check_secrets.outputs.defined}}
    steps:
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
      - name: Check for Secrets availabilities
        id: check_secrets
        shell: bash
        run: |
          if [[ -n "${{ secrets.BASE64_PEM }}" ]]; then
            echo "${{ toJson(secrets) }}";
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "${{ toJson(secrets) }}"
            echo "is undefined";
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    environment: production
    needs: checking-secrets
    if: needs.checking-secrets.outputs.secret_key_exists == 'true'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Add environment variables to .env
        run: |
          echo API_IMAGE=${{ env.API_IMAGE }} >> .env
          echo NGINX_IMAGE=${{ env.NGINX_IMAGE }} >> .env
          echo NAMESPACE=${{ github.repository_owner }} >> .env
          echo PERSONAL_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }} >> .env
#      - name: Decode SSH private key
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#
#      - name: Set up SSH
#        run: |
#          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
#          ssh-keyscan github.com >> ~/.ssh/known_hosts
#          chmod 600 ~/.ssh/id_rsa
      - name: Decode SSH private key
        run: |
          echo "${{ secrets.BASE64_PEM }}" | base64 -d > private_key.pem
          chmod 600 private_key.pem

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          mv private_key.pem ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PUBLIC_IPV4_DNS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_rsa
#      - name: Add the private SSH key to the ssh-agent
#        env:
#          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
#        run: |
#          mkdir -p ~/.ssh
#          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
#          ssh-keyscan github.com >> ~/.ssh/known_hosts
#          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
#          echo "ls ~/.ssh/"
#      - name: Add the private SSH key to the ssh-agent
#        env:
#          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#
#        run: |
#          mkdir -p ~/.ssh
#          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
#          ssh-keyscan github.com >> ~/.ssh/known_hosts
#          chmod 400 "$SSH_PRIVATE_KEY"
#          printf "%s" "${SSH_PRIVATE_KEY}" | ssh-add -
#          chmod 700 ~/.ssh
      - name: Deploy images on AWS EC2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

        run: |
          scp -o StrictHostKeyChecking=no -r ./.env ./docker-compose.prod.yml ${{secrets.AWS_USER}}@${{ secrets.PUBLIC_IPV4_DNS }}:
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{secrets.AWS_USER}}@${{ secrets.PUBLIC_IPV4_DNS }} << EOF
          
              echo "connected"
              sudo docker-compose down --rmi all -v
              echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
              echo ${{ env.API_IMAGE }}
              sudo docker pull ${{ env.API_IMAGE }}
              sudo docker pull ${{ env.NGINX_IMAGE }}
              sudo docker-compose --env-file=.env -f docker-compose.prod.yml up -d --build
              sudo docker logout
          EOF

#  docker login ghcr.io -u ${{ github.repository_owner }} -p ${{secrets.GITHUB_TOKEN}}
#  ssh -o StrictHostKeyChecking=no ${{secrets.HOST}}@${{ secrets.AWS_EC2_IP_ADDRESS }} << EOF
#  scp -o StrictHostKeyChecking=no -r ./.env ./docker-compose.prod.yml ${{secrets.HOST}}@${{ secrets.AWS_EC2_IP_ADDRESS }}:
#  ssh -o StrictHostKeyChecking=no ${{secrets.HOST}}@${{ secrets.AWS_EC2_IP_ADDRESS }} << EOF